### mono-zip
GET localhost:8080/mono-zip

###
GET localhost:8080/flux-flatmap

###
GET localhost:8080/flux-merge

###
GET localhost:8080/mono-retry-timeout

###
GET localhost:8080/web-exchange-filter


### WIREMOCK
###
GET localhost:9100/numeric

###
GET localhost:9100/time

###
GET localhost:9100/400